# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scara_robot_arm_controller
    - scara_robot_hand_controller

  scara_robot_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    action_ns: follow_joint_trajectory
    default: true
  scara_robot_hand_controller:
    type: GripperCommand
    joints:
      - joint_gripper
    action_ns: gripper_cmd
    default: true