# Default initial positions for denso_vp6242's ros2_control fake system

initial_positions:
  joint_1: 0.0
  joint_2: 0.0
  joint_3: 1.570796
  joint_4: 0.0
  joint_5: 0.0
  joint_6: 0.0
  joint_gripper: 0.0