# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.40317105721069005
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.392175482923126
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.72570790297924205
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.73914693821959901
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.73914693821959901
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.1093312725675999
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_gripper:
    has_velocity_limits: true
    max_velocity: 0.100
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_gripper_mimic:
    has_velocity_limits: true
    max_velocity: 0.100
    has_acceleration_limits: true
    max_acceleration: 1.0