# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1:
    has_position_limits: true
    max_position: 2.617994
    min_position: -2.617994
    has_velocity_limits: true
    max_velocity: 1.0 #40.317105721069005
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_2:
    has_position_limits: true
    max_position: 1.745329
    min_position: -1.047198
    has_velocity_limits: true
    max_velocity: 1.0 #39.2175482923126
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_3:
    has_position_limits: true
    max_position: 2.443461
    min_position: 0.3141593
    has_velocity_limits: true
    max_velocity: 1.8 #72.570790297924205
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_4:
    has_position_limits: true
    max_position: 2.96706
    min_position: -2.96706
    has_velocity_limits: true
    max_velocity: 1.8 #73.914693821959901
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_5:
    has_position_limits: true
    max_position: 2.356194
    min_position: -1.658063
    has_velocity_limits: true
    max_velocity: 1.8 #73.914693821959901
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_6:
    has_position_limits: true
    max_position: 2.96706
    min_position: -2.96706
    has_velocity_limits: true
    max_velocity: 2.5 #110.93312725675999
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_gripper:
    has_velocity_limits: true
    max_velocity: 10.0 #1800.0
    has_acceleration_limits: true
    max_acceleration: 1.0
  joint_gripper_mimic:
    has_velocity_limits: true
    max_velocity: 10.0 #1800.0
    has_acceleration_limits: true
    max_acceleration: 1.0