# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - vp6242_arm_controller
    - vp6242_hand_controller

  vp6242_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
    action_ns: follow_joint_trajectory
    default: true
  vp6242_hand_controller:
    type: GripperCommand
    joints:
      - right_claw_joint
    action_ns: gripper_cmd
    default: true