block_printer:
  motion_commander:
    manipulator:
      command_type: move
      pose_reference: base_link
      pose_type: EulerFrame
      initial_pose: {position: [0.18,0,0.4], orientation: [-7.03047e-7,5.70387e-6,-0.720089,0.693882]}
      finish_pose: {position: [0.16,0,0.45], orientation: [-7.03047e-7,5.70387e-6,-0.720089,0.693882]}
      velocity: {type: "factor", high: [1.0], low: [0.2]}
      acceleration: {type: "factor", high: [1.0], low: [1.0]}
      force_threshold: {type: "percent", high: [100,100,100,100,100,100], low: [100,100,70,100,100,100]}
    gripper:
      command_type: gripper
      poses: [0, 0.038, 0.0341]
      margin: -0.001
      effort: 50
