#define block_size 0.3
#define table_x_size 30.0
#define table_y_size 20.0
#define table_z_size 20.0
#define base_x_size 15.0
#define base_y_size 15.0
#define base_z_size 0.2
#define dispenser_x_size 2.4
#define dispenser_y_size 12.0
#define dispenser_z_size 0.2
#define minimum_resolution 0.01
#define WHITE 0
#define RED 1
#define ORANGE 2
#define YELLOW 3
#define GREEN 4
#define BLUE 5
#define BLACK 6
#define SUPPORT 7
#define ONE_ROW 1
#define TWO_ROW 0
#define INSERT_DISTANCE 1.5
#define CLAW_STOP_DISTANCE 6.15