#define block_size 0.3
#define table_x_size 30.0
#define table_y_size 20.0
#define table_z_size 25.0
#define base_x_size 6.0
#define base_y_size 6.0
#define base_z_size 0.2
#define dispenser_x_size 2.4
#define dispenser_y_size 12.0
#define dispenser_z_size 0.2
#define minimum_resolution 0.01
#define WHITE 1
#define RED 2
#define ORANGE 3
#define YELLOW 4
#define GREEN 5
#define BLUE 6
#define BLACK 7
#define SUPPORT 0