# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - epson_t3_arm_controller
    - epson_t3_hand_controller

  epson_t3_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
    action_ns: follow_joint_trajectory
    default: true
  epson_t3_hand_controller:
    type: GripperCommand
    joints:
      - joint_gripper
    action_ns: gripper_cmd
    default: true