#position: [x, y, z]...meter value
#orientation: [roll, pitch, yaw]...radian value
block_printer:
  pick0:
    block: {size_x: 1,size_y: 1, color: "white"}
    position: [0.34165,-0.04047,0.24836] 
    orientation: [0,0,1.57]
  pick1:
    block: {size_x: 1,size_y: 1, color: "red"}
    position: [0.34156,-0.04592,0.24812] 
    orientation: [0,0,1.57]
  pick2:
    block: {size_x: 1,size_y: 1, color: "orange"}
    position: [0.34133,-0.05171,0.24836] 
    orientation: [0,0,1.57]
  pick3:
    block: {size_x: 1,size_y: 1, color: "yellow"}
    position: [0.34112,-0.05820,0.24813]
    orientation: [0,0,1.57]
  pick4:
    block: {size_x: 1,size_y: 1, color: "green"}
    position: [0.34074,-0.06426,0.24848] 
    orientation: [0,0,1.57]
  pick5:
    block: {size_x: 1,size_y: 1, color: "blue"}
    position: [0.34073,-0.07008,0.24813] 
    orientation: [0,0,1.57]
  pick6:
    block: {size_x: 1,size_y: 1, color: "black"}
    position: [0.34023,-0.07546,0.24834] 
    orientation: [0,0,1.57]
  pick7:
    block: {size_x: 1,size_y: 1, color: "support"}
    position: [0.33993,-0.08160,0.24818] 
    orientation: [0,0,1.57]
  pick8:
    block: {size_x: 2,size_y: 1, color: "white"}
    position: [0.34304,0.00256,0.24838] 
    orientation: [0,0,1.57]
  pick9:
    block: {size_x: 2,size_y: 1, color: "red"}
    position: [0.34289,-0.00291,0.24822] 
    orientation: [0,0,1.57]
  pick10:
    block: {size_x: 2,size_y: 1, color: "orange"}
    position: [0.34254,-0.00900,0.24829] 
    orientation: [0,0,1.57]
  pick11:
    block: {size_x: 2,size_y: 1, color: "yellow"}
    position: [0.34263,-0.01464,0.24816] 
    orientation: [0,0,1.57]
  pick12:
    block: {size_x: 2,size_y: 1, color: "green"}
    position: [0.34241,-0.02055,0.24808] 
    orientation: [0,0,1.57]
  pick13:
    block: {size_x: 2,size_y: 1, color: "blue"}
    position: [0.34225,-0.02728,0.24816] 
    orientation: [0,0,1.57]
  pick14:
    block: {size_x: 2,size_y: 1, color: "black"}
    position: [0.34188,-0.03275,0.24811] 
    orientation: [0,0,1.57]
  pick15:
    block: {size_x: 2,size_y: 2, color: "white"}
    position: [0.34485,0.07184,0.24877]
    orientation: [0,0,1.57]
  pick16:
    block: {size_x: 2,size_y: 2, color: "red"}
    position: [0.34497,0.06296,0.24854]
    orientation: [0,0,1.57]
  pick17:
    block: {size_x: 2,size_y: 2, color: "orange"}
    position: [0.34482,0.05213,0.24846]
    orientation: [0,0,1.57]
  pick18:
    block: {size_x: 2,size_y: 2, color: "yellow"}
    position: [0.34417,0.04264,0.24841]
    orientation: [0,0,1.57]
  pick19:
    block: {size_x: 2,size_y: 2, color: "green"}
    position: [0.34387,0.03248,0.24852]
    orientation: [0,0,1.57]
  pick20:
    block: {size_x: 2,size_y: 2, color: "blue"}
    position: [0.34349,0.02327,0.24831]
    orientation: [0,0,1.57]
  pick21:
    block: {size_x: 2,size_y: 2, color: "black"}
    position: [0.34310,0.01276,0.24823]
    orientation: [0,0,1.57]
