block_printer:
  motion_commander:
    manipulator:
      command_type: move
      pose_reference: base_link
      pose_type: EulerFrame
      initial_pose: {position: [0.2,0,0.35], orientation: [0,0,-0.70711,0.70711]}
      finish_pose: {position: [0.2,0,0.35], orientation: [0,0,-0.70711,0.70711]}
      velocity: {type: "factor", high: [1], low: [0.2]}
      acceleration: {type: "factor", high: [1,1,1], low: [1,1,1]}
      force_threshold: {type: "factor", high: [1,1,1], low: [1,1,0.7]}
    gripper:
      command_type: gripper
      poses: [0, 0.038, 0.0324]
      margin: -0.001
      effort: 50
