<?xml version="1.0"?>
<robot name="cartesian_robot_block_printer" 
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="width" value="0.07" />
    <xacro:property name="base_height" value="1.0" />
    <xacro:property name="height1" value="0.5" />
    <xacro:property name="height2" value="0.35" />
    <xacro:property name="height3" value="0.3" />
    <xacro:property name="height4" value="0.5" />
    <xacro:property name="height5" value="0.05" />
    <xacro:property name="prismatic_velocity" value="1.0"/>
    <xacro:property name="prismatic_effort" value="100.0"/>
    <xacro:property name="revolute_velocity" value="3.0"/>
    <xacro:property name="revolute_effort" value="10.0"/>
    <xacro:property name="mass" value="0.1"/>

    <xacro:include filename="$(find urdf_macro)/urdf/material.xacro" />
    <xacro:include filename="$(find urdf_macro)/urdf/primitive_shape.xacro" />

    <link name="base_link"/>
    <xacro:rectangle_link name="link1" x="${width}" y="${width}" z="${height1}" mass="${mass}" rgba="1 1 1 1" />
    <xacro:rectangle_link name="link2" x="${width}" y="${width}" z="${height2}" mass="${mass}" rgba="1 0 0 1" />
    <xacro:rectangle_link name="link3" x="${width}" y="${width}" z="${height3}" mass="${mass}" rgba="0 1 0 1" />
    <xacro:rectangle_link name="link4" x="${width}" y="${width}" z="${height4}" mass="${mass}" rgba="0 0 1 1" />
    <xacro:cylinder_link name="link5" radius="${width/2}" length="${height5}" mass="${mass}" rgba="1 1 0 1" />
    <link name="tool0" />

    <joint name="base_joint" type="fixed">
        <parent link="base_link"/>
        <child link="link1"/>
        <origin xyz="0 0 ${base_height / 2}" rpy="0 ${pi / 2} ${-pi/2}"/>
        <axes xyz="1 0 0" />
    </joint>

    <joint name="joint1" type="prismatic">
        <parent link="link1"/>
        <child link="link2"/>
        <origin xyz="0 ${width / 2} ${height1 - width / 2}" rpy="-${pi / 2} ${pi / 2} 0"/>
        <limit lower="0" upper="${height1 -width}" effort="${prismatic_effort}" velocity="${prismatic_velocity}"/>
    </joint>

    <joint name="joint2" type="prismatic">
        <parent link="link2"/>
        <child link="link3"/>
        <origin xyz="${width / 2} 0 ${height2 - width / 2}" rpy="0 ${pi / 2} 0"/>
        <limit lower="0" upper="${height2 - width}" effort="${prismatic_effort}" velocity="${prismatic_velocity}"/>
    </joint>

    <joint name="joint3" type="prismatic">
        <parent link="link3"/>
        <child link="link4"/>
        <origin xyz="0 ${height4 / 2 + width / 2} ${height3 + width / 2}" rpy="${pi / 2} 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-1 * height4 / 2}" upper="${height4 / 2}" effort="${prismatic_effort}" velocity="${prismatic_velocity}"/>
    </joint>

    <joint name="joint4" type="revolute">
        <parent link="link4"/>
        <child link="link5"/>
        <origin xyz="0 0 ${height4}" rpy="0 0 0"/>
        <axis xyz="0 0 1"/>
        <limit lower="${-pi}" upper="${pi}" effort="${revolute_effort}" velocity="${revolute_velocity}"/>
    </joint>

    <joint name="tool_joint" type="fixed">
        <origin xyz="0.0 0.0 ${height5}" rpy="0.0 0.0 0.0"/>
        <parent link="link5"/>
        <child link="tool0"/>
    </joint>

    <!--merge gripper-->
    <xacro:include filename="$(find gripper_description)/urdf/simple_esg1_fs_2840_macro.xacro">
        <arg name="robot_tool_link" value="tool0"/>
        <arg name="tool_roll" value="0"/>
        <arg name="tool_pitch" value="3.141592653589793238"/>
        <arg name="tool_yaw" value="0"/>
    </xacro:include>
</robot>
