# Default initial positions for denso_cobotta's ros2_control fake system

initial_positions:
  joint_1: 1.5708
  joint_2: 0
  joint_3: 1.5708
  joint_4: 0
  joint_5: 0
  joint_6: 0
  joint_gripper: 0
